services:
  web:
    build:
      context: ./WebApi
      dockerfile: Dockerfile
      target: dev
    image: webapi-dev:latest
    ports:
      - "${WEB_PORT}:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__PostgresConnection=Host=db;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
    networks:
      - internal_net
    depends_on:
      - db
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:${WEB_PORT}/status" ]
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 30s

  db:
    image: postgres:18
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata_dev:/var/lib/postgresql
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - internal_net

networks:
  internal_net:
    name: internal_net

volumes:
  pgdata_dev:
