COMPOSE_DEV=docker-compose.dev.yml
COMPOSE_PRO=docker-compose.pro.yml
DEV_ENV = .env.dev
PRO_ENV = .env.pro

# Construir imagenes dev-pro
build-dev:
	docker compose -f $(COMPOSE_DEV) --env-file $(DEV_ENV) build

build-pro:
	docker compose -f $(COMPOSE_PRO) --env-file $(PRO_ENV) build

# Levantar entornos dev-pro
up-dev:
	docker compose -f $(COMPOSE_DEV) --env-file $(DEV_ENV) up -d --build

up-pro:
	docker compose -f $(COMPOSE_PRO) --env-file $(PRO_ENV) up -d --build
	
# Dentener entornos dev-pro
down-dev:
	docker compose -f $(COMPOSE_DEV) --env-file $(DEV_ENV) down

down-pro:
	docker compose -f $(COMPOSE_PRO) --env-file $(PRO_ENV) down

# Limpiar entornos dev-pro
clean-dev:
	docker compose -f $(COMPOSE_DEV) --env-file $(DEV_ENV) down -v --rmi local --remove-orphans

clean-pro:
	docker compose -f $(COMPOSE_PRO) --env-file $(PRO_ENV) down -v --rmi local --remove-orphans
