version: '3.9'
services:
  web:
    image: nginx:alpine
    env_file: .env
    ports:
      - "${WEB_PORT}:80"
    networks:
      - internal_net
    depends_on:
      - db
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:${WEB_PORT}/healthcheck" ]
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 30s
    volumes:
      #- ./default.conf:/etc/nginx/conf.d/default.conf
      - ./index.html:/usr/share/nginx/html/index.html
      #- ./healthcheck.html:/usr/share/nginx/html/healthcheck.html


  db:
    image: mysql:8.0
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - internal_net

networks:
  internal_net:
    name: internal_net

volumes:
  db_data:
